In [2]:
import numpy as np 

In [3]:
arr_new=np.arange(20)
print(arr_new[2:10])

[2 3 4 5 6 7 8 9]


In [4]:
arr_new2=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(arr_new2[1,2])#it slice the 2D array and give the index values 

6


In [5]:
unsortarr=np.array([3,4,2,1,5,9,7,6])
print(np.sort(unsortarr))
#sorting array 1d and 2d 
unsortarr_2d=np.array([[3,4],
                       [5,1],
                       [9,1]])
print(np.sort(unsortarr_2d,axis=0))#if you give axis is o it sort the whole colum and axis 1 sort the row vise data 

[1 2 3 4 5 6 7 9]
[[3 1]
 [5 1]
 [9 4]]


In [6]:
arr_new=np.arange(20)
even_num=arr_new[arr_new % 2 ==0]#index value perfrom the opration aslo in numpy only not in python 
print(even_num)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
mask=arr_new > 10
#mask store the full exp. with its out put 
print(arr_new[mask])

[11 12 13 14 15 16 17 18 19]


In [8]:
where_re=np.where(arr_new>10)
print(where_re)
print(arr_new[where_re])

(array([11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)
[11 12 13 14 15 16 17 18 19]


In [9]:
conditions=np.where(arr_new >10,arr_new,arr_new)
print(conditions)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
combine=np.concatenate((arr1,arr2))
print(combine)#it is use to combine the array 
print(arr1.shape == arr2.shape)

[1 2 3 4 5 6 7 8 9]
False
