In [1]:
import numpy as np

In [ ]:
#simple array using numpy 
arr_np = np.array([1,2,3,4])
print("This is 1D array:\n",arr_np)

arr_np2 = np.array([[1,2,3,4],
                    [2,3,4,5]])
print("This is 2D array :\n",arr_np2)

This is 1D array:
 [1 2 3 4]
This is 2D array :
 [[1 2 3 4]
 [2 3 4 5]]


In [ ]:
#opartion in numpy 
arr_np=([1,2,3,4])*2
print(arr_np)

[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
import time 
start=time.time()
arr_np=([1,2,3,4])*2
print(time.time()-start)#print the time required for op.

0.0


In [ ]:
zeros=np.zeros([3,5])#creates the array of all zeros 
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
full=np.full((5,3),8)#create the array of specifice number 
print(full)

[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [ ]:
random=np.random.random((3,5))#create the array with random values 
print(random)

[[0.17928481 0.71057323 0.8989461  0.75299959 0.30746177]
 [0.53980269 0.919965   0.96220692 0.88932305 0.49692349]
 [0.20704406 0.72695469 0.64465125 0.92236133 0.07382781]]


In [ ]:
sequ=np.arange(0,20,2)#it gives the sequens of array elements
print(sequ)

[ 0  2  4  6  8 10 12 14 16 18]


In [22]:
vector=np.array([1,2,3,4,5])
print(vector)

[1 2 3 4 5]


In [23]:
matrix=np.array([[1,2,3],
                 [5,6,7]])
print(matrix)

[[1 2 3]
 [5 6 7]]


In [25]:
tensor=np.array([[[1,3],[3,4]],
                  [[2,4],[4,5]],
                  [[6,7],[8,9]]])
print(tensor)

[[[1 3]
  [3 4]]

 [[2 4]
  [4 5]]

 [[6 7]
  [8 9]]]


In [ ]:
arr = np.array([[1,2,3,4],
                [2,3,4,5]])
print(arr.size)#for the size of array
print(arr.dtype)#for data type of array
print(arr.ndim)#for geting the dime.
print(arr.shape)#for the shape 

8
int32
2
(2, 4)


In [ ]:
arr_new=np.arange(0,20)
reshaped = arr_new.reshape((4,5))#it re-shape the array in given size 
print("it re-shape the array in given size",reshaped)

flattened=arr_new.flatten()#it convert the array in orignal form 
print("it convert the array in orignal form ",flattened)

revel=arr_new.ravel() #it print the copy of the array 
print("it print the copy of the array ",revel)

it re-shape the array in given size [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
*****
it convert the array in orignal form  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
it print the copy of the array  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
