In [1]:
import numpy as np 
import matplotlib.pyplot as plt 

In [4]:
arr1 = np.random.rand(3,3)
array1=np.save('array1.npy',arr1)

In [5]:
load_arr1=np.load('array1.npy')
print(load_arr1)

[[0.62449265 0.27099722 0.01041611]
 [0.24326605 0.02809374 0.53895002]
 [0.26003937 0.31440297 0.66895415]]
